apiVersion: v1
kind: Service
metadata:
  name: binarycalculator-service
  labels:
    app: binarycalculator
spec:
  type: LoadBalancer  # Use NodePort if not deploying on GKE
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: binarycalculator
