apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculator-deployment
  labels:
    app: binarycalculator
spec:
  replicas: 2  # Adjust based on your scaling needs
  selector:
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: northamerica-northeast2-docker.pkg.dev/helical-analyst-452016-b8/sofe3980u/binarycalculator:v3
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: gcr-secret  
